"""initial schema

Revision ID: 88fee68e6413
Revises:
Create Date: 2026-08-19 01:59:38.919886

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "88fee68e6413"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("correlation_id", sa.String(length=64), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=False),
        sa.Column("actor_role", sa.String(length=32), nullable=False),
        sa.Column("result", sa.Text(), nullable=False),
        sa.Column("agent_version", sa.String(length=64), nullable=True),
        sa.Column("model_id", sa.String(length=128), nullable=True),
        sa.Column("policy_version", sa.String(length=64), nullable=True),
        sa.Column(
            "detail", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        "ix_audit_correlation_time", "audit_events", ["correlation_id", "occurred_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_correlation_id"), "audit_events", ["correlation_id"], unique=False
    )
    op.create_index(op.f("ix_audit_events_stage"), "audit_events", ["stage"], unique=False)
    op.create_table(
        "dead_letters",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("correlation_id", sa.String(length=64), nullable=False),
        sa.Column("document_hash", sa.String(length=64), nullable=True),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column("detail", sa.Text(), server_default="", nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dead_letters")),
    )
    op.create_index(
        op.f("ix_dead_letters_correlation_id"), "dead_letters", ["correlation_id"], unique=False
    )
    op.create_table(
        "erp_transactions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("correlation_id", sa.String(length=64), nullable=False),
        sa.Column("invoice_id", sa.String(length=64), nullable=True),
        sa.Column("erp_transaction_id", sa.String(length=128), nullable=True),
        sa.Column("adapter", sa.String(length=64), nullable=False),
        sa.Column("posted_amount", sa.Numeric(), nullable=True),
        sa.Column("posted_currency", sa.String(length=3), nullable=True),
        sa.Column("succeeded", sa.Boolean(), nullable=False),
        sa.Column("message", sa.Text(), server_default="", nullable=False),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "NOT succeeded OR erp_transaction_id IS NOT NULL",
            name=op.f("ck_erp_transactions_success_identifies_transaction"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_erp_transactions")),
    )
    op.create_index(
        op.f("ix_erp_transactions_correlation_id"),
        "erp_transactions",
        ["correlation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_erp_transactions_idempotency_key"),
        "erp_transactions",
        ["idempotency_key"],
        unique=True,
    )
    op.create_table(
        "policy_versions",
        sa.Column("policy_version_id", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=False),
        sa.Column("rules", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("policy_version_id", name=op.f("pk_policy_versions")),
    )
    op.create_index(
        op.f("ix_policy_versions_is_active"), "policy_versions", ["is_active"], unique=False
    )
    op.create_table(
        "vendors",
        sa.Column("vendor_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("first_seen", sa.Date(), nullable=True),
        sa.Column("invoice_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("mean_invoice_amount", sa.Numeric(), nullable=True),
        sa.Column("max_invoice_amount", sa.Numeric(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.CheckConstraint(
            "invoice_count >= 0", name=op.f("ck_vendors_invoice_count_non_negative")
        ),
        sa.PrimaryKeyConstraint("vendor_id", name=op.f("pk_vendors")),
    )
    op.create_index(op.f("ix_vendors_name"), "vendors", ["name"], unique=False)
    op.create_table(
        "invoices",
        sa.Column("invoice_id", sa.String(length=64), nullable=False),
        sa.Column("correlation_id", sa.String(length=64), nullable=False),
        sa.Column("document_hash", sa.String(length=64), nullable=False),
        sa.Column("storage_uri", sa.Text(), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("vendor_id", sa.String(length=64), nullable=True),
        sa.Column("invoice_number", sa.String(length=128), nullable=True),
        sa.Column("normalized_invoice_number", sa.String(length=128), nullable=True),
        sa.Column("po_number", sa.String(length=64), nullable=True),
        sa.Column("invoice_date", sa.Date(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("total_due", sa.Numeric(), nullable=True),
        sa.Column("extraction", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("validation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("duplicates", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("risk", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reasoning", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("policy_decision", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("risk_score", sa.Numeric(), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("size_bytes > 0", name=op.f("ck_invoices_size_positive")),
        sa.ForeignKeyConstraint(
            ["vendor_id"], ["vendors.vendor_id"], name=op.f("fk_invoices_vendor_id_vendors")
        ),
        sa.PrimaryKeyConstraint("invoice_id", name=op.f("pk_invoices")),
    )
    op.create_index(op.f("ix_invoices_correlation_id"), "invoices", ["correlation_id"], unique=True)
    op.create_index(op.f("ix_invoices_document_hash"), "invoices", ["document_hash"], unique=False)
    op.create_index(op.f("ix_invoices_po_number"), "invoices", ["po_number"], unique=False)
    op.create_index("ix_invoices_queue", "invoices", ["status", "risk_score"], unique=False)
    op.create_index(op.f("ix_invoices_status"), "invoices", ["status"], unique=False)
    op.create_index(op.f("ix_invoices_vendor_id"), "invoices", ["vendor_id"], unique=False)
    op.create_index(
        "ix_invoices_vendor_number",
        "invoices",
        ["vendor_id", "normalized_invoice_number"],
        unique=False,
    )
    op.create_table(
        "purchase_orders",
        sa.Column("po_number", sa.String(length=64), nullable=False),
        sa.Column("vendor_id", sa.String(length=64), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("issued_date", sa.Date(), nullable=False),
        sa.Column("approved_shipping", sa.Numeric(), nullable=True),
        sa.ForeignKeyConstraint(
            ["vendor_id"], ["vendors.vendor_id"], name=op.f("fk_purchase_orders_vendor_id_vendors")
        ),
        sa.PrimaryKeyConstraint("po_number", name=op.f("pk_purchase_orders")),
    )
    op.create_index(
        op.f("ix_purchase_orders_vendor_id"), "purchase_orders", ["vendor_id"], unique=False
    )
    op.create_table(
        "vendor_bank_accounts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("vendor_id", sa.String(length=64), nullable=False),
        sa.Column("account_fingerprint", sa.String(length=128), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.vendor_id"],
            name=op.f("fk_vendor_bank_accounts_vendor_id_vendors"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendor_bank_accounts")),
        sa.UniqueConstraint("vendor_id", "effective_from", name="uq_vendor_bank_effective"),
    )
    op.create_index(
        op.f("ix_vendor_bank_accounts_vendor_id"),
        "vendor_bank_accounts",
        ["vendor_id"],
        unique=False,
    )
    op.create_table(
        "vendor_contracts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("vendor_id", sa.String(length=64), nullable=False),
        sa.Column("pricing_terms", sa.Text(), server_default="", nullable=False),
        sa.Column("shipping_allowed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("max_shipping", sa.Numeric(), nullable=True),
        sa.Column("max_shipping_currency", sa.String(length=3), nullable=True),
        sa.Column("price_tolerance_pct", sa.Numeric(), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to >= effective_from",
            name=op.f("ck_vendor_contracts_effective_dates_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"], ["vendors.vendor_id"], name=op.f("fk_vendor_contracts_vendor_id_vendors")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendor_contracts")),
    )
    op.create_index(
        op.f("ix_vendor_contracts_vendor_id"), "vendor_contracts", ["vendor_id"], unique=False
    )
    op.create_table(
        "goods_receipts",
        sa.Column("grn_number", sa.String(length=64), nullable=False),
        sa.Column("po_number", sa.String(length=64), nullable=False),
        sa.Column("received_date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["po_number"],
            ["purchase_orders.po_number"],
            name=op.f("fk_goods_receipts_po_number_purchase_orders"),
        ),
        sa.PrimaryKeyConstraint("grn_number", name=op.f("pk_goods_receipts")),
    )
    op.create_index(
        op.f("ix_goods_receipts_po_number"), "goods_receipts", ["po_number"], unique=False
    )
    op.create_table(
        "purchase_order_lines",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("po_number", sa.String(length=64), nullable=False),
        sa.Column("item_id", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("agreed_unit_price", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("approved_qty", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.CheckConstraint(
            "approved_qty > 0", name=op.f("ck_purchase_order_lines_approved_qty_positive")
        ),
        sa.ForeignKeyConstraint(
            ["po_number"],
            ["purchase_orders.po_number"],
            name=op.f("fk_purchase_order_lines_po_number_purchase_orders"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_order_lines")),
        sa.UniqueConstraint("po_number", "item_id", name="uq_po_line_item"),
    )
    op.create_index(
        op.f("ix_purchase_order_lines_po_number"),
        "purchase_order_lines",
        ["po_number"],
        unique=False,
    )
    op.create_table(
        "goods_receipt_lines",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("grn_number", sa.String(length=64), nullable=False),
        sa.Column("item_id", sa.String(length=64), nullable=False),
        sa.Column("received_qty", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "damaged_qty", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False
        ),
        sa.CheckConstraint(
            "damaged_qty <= received_qty",
            name=op.f("ck_goods_receipt_lines_damaged_within_received"),
        ),
        sa.CheckConstraint(
            "damaged_qty >= 0", name=op.f("ck_goods_receipt_lines_damaged_qty_non_negative")
        ),
        sa.CheckConstraint(
            "received_qty >= 0", name=op.f("ck_goods_receipt_lines_received_qty_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["grn_number"],
            ["goods_receipts.grn_number"],
            name=op.f("fk_goods_receipt_lines_grn_number_goods_receipts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_goods_receipt_lines")),
        sa.UniqueConstraint("grn_number", "item_id", name="uq_grn_line_item"),
    )
    op.create_index(
        op.f("ix_goods_receipt_lines_grn_number"),
        "goods_receipt_lines",
        ["grn_number"],
        unique=False,
    )
    # ### end Alembic commands ###

    # -----------------------------------------------------------------------------------
    # The audit log is append-only. Spec §12 calls it immutable; a convention that
    # developers respect is not immutability, so the database itself refuses the write.
    #
    # This binds the application's own role too, which is the point: DoD-5 requires every
    # financial action to be reproducible from this log, and a log that can be quietly
    # edited proves nothing about what actually happened.
    # -----------------------------------------------------------------------------------
    op.execute(
        """
        CREATE OR REPLACE FUNCTION sentinel_audit_is_append_only()
        RETURNS TRIGGER AS $$
        BEGIN
            RAISE EXCEPTION
                'audit_events is append-only: % on event_id % was refused',
                TG_OP, COALESCE(OLD.event_id, NEW.event_id)
                USING HINT = 'Correct a mistaken event by appending a corrective event.';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER audit_events_append_only
        BEFORE UPDATE OR DELETE ON audit_events
        FOR EACH ROW EXECUTE FUNCTION sentinel_audit_is_append_only();
        """
    )

    # A policy version is immutable for the same reason: spec §9 requires a historical
    # decision to be replayable against the exact rules that produced it, and editing a
    # version in place would silently rewrite the past. Activation is the one legitimately
    # mutable aspect, so the trigger permits an is_active flip and refuses everything else.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION sentinel_policy_rules_are_immutable()
        RETURNS TRIGGER AS $$
        BEGIN
            IF (NEW.policy_version_id, NEW.label, NEW.rules, NEW.created_at, NEW.created_by)
               IS DISTINCT FROM
               (OLD.policy_version_id, OLD.label, OLD.rules, OLD.created_at, OLD.created_by)
            THEN
                RAISE EXCEPTION
                    'policy version % is immutable; publish a new version instead',
                    OLD.policy_version_id
                    USING HINT = 'Only is_active may change on an existing policy version.';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER policy_versions_immutable
        BEFORE UPDATE ON policy_versions
        FOR EACH ROW EXECUTE FUNCTION sentinel_policy_rules_are_immutable();
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS policy_versions_immutable ON policy_versions;")
    op.execute("DROP FUNCTION IF EXISTS sentinel_policy_rules_are_immutable();")
    op.execute("DROP TRIGGER IF EXISTS audit_events_append_only ON audit_events;")
    op.execute("DROP FUNCTION IF EXISTS sentinel_audit_is_append_only();")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_goods_receipt_lines_grn_number"), table_name="goods_receipt_lines")
    op.drop_table("goods_receipt_lines")
    op.drop_index(op.f("ix_purchase_order_lines_po_number"), table_name="purchase_order_lines")
    op.drop_table("purchase_order_lines")
    op.drop_index(op.f("ix_goods_receipts_po_number"), table_name="goods_receipts")
    op.drop_table("goods_receipts")
    op.drop_index(op.f("ix_vendor_contracts_vendor_id"), table_name="vendor_contracts")
    op.drop_table("vendor_contracts")
    op.drop_index(op.f("ix_vendor_bank_accounts_vendor_id"), table_name="vendor_bank_accounts")
    op.drop_table("vendor_bank_accounts")
    op.drop_index(op.f("ix_purchase_orders_vendor_id"), table_name="purchase_orders")
    op.drop_table("purchase_orders")
    op.drop_index("ix_invoices_vendor_number", table_name="invoices")
    op.drop_index(op.f("ix_invoices_vendor_id"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_status"), table_name="invoices")
    op.drop_index("ix_invoices_queue", table_name="invoices")
    op.drop_index(op.f("ix_invoices_po_number"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_document_hash"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_correlation_id"), table_name="invoices")
    op.drop_table("invoices")
    op.drop_index(op.f("ix_vendors_name"), table_name="vendors")
    op.drop_table("vendors")
    op.drop_index(op.f("ix_policy_versions_is_active"), table_name="policy_versions")
    op.drop_table("policy_versions")
    op.drop_index(op.f("ix_erp_transactions_idempotency_key"), table_name="erp_transactions")
    op.drop_index(op.f("ix_erp_transactions_correlation_id"), table_name="erp_transactions")
    op.drop_table("erp_transactions")
    op.drop_index(op.f("ix_dead_letters_correlation_id"), table_name="dead_letters")
    op.drop_table("dead_letters")
    op.drop_index(op.f("ix_audit_events_stage"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_correlation_id"), table_name="audit_events")
    op.drop_index("ix_audit_correlation_time", table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
